---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2 # Desired number of Nginx pods
  selector:
    matchLabels:
      app: nginx # Selects pods with this label to be managed by this Deployment
  template:
    metadata:
      labels:
        app: nginx # Labels applied to the pods created by this Deployment
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest # The Docker image to use
        ports:
        - containerPort: 80 # The port the Nginx container listens on
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    app: nginx # Selects pods with this label to expose via this Service
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 80 # Port on the Pod that the Service forwards to
  type: ClusterIP # Exposes the Service on an internal IP in the cluster
